<<<<<<< HEAD
# Generated by Django 3.2.5 on 2021-07-08 17:55

import cloudinary.models
=======
# Generated by Django 3.2.4 on 2021-06-16 20:10

>>>>>>> 8bd5679f0915566d6e588b99e4c05e916e2e99f6
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='brands',
            fields=[
<<<<<<< HEAD
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
=======
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
>>>>>>> 8bd5679f0915566d6e588b99e4c05e916e2e99f6
                ('NameA', models.TextField(max_length=2550, null=True)),
                ('NameL', models.TextField(max_length=2550)),
            ],
        ),
        migrations.CreateModel(
            name='cartTransactionMasters',
            fields=[
<<<<<<< HEAD
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
=======
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
>>>>>>> 8bd5679f0915566d6e588b99e4c05e916e2e99f6
                ('DateCreated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='cartTransactions',
            fields=[
<<<<<<< HEAD
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.FloatField()),
                ('IsOrdered', models.IntegerField()),
                ('MasterId', models.ForeignKey(db_column='MasterId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.carttransactionmasters')),
=======
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.FloatField()),
                ('IsOrdered', models.IntegerField()),
                ('MasterId', models.ForeignKey(db_column='MasterId', db_constraint=False,
                 on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.carttransactionmasters')),
>>>>>>> 8bd5679f0915566d6e588b99e4c05e916e2e99f6
            ],
        ),
        migrations.CreateModel(
            name='categories',
            fields=[
<<<<<<< HEAD
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
=======
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
>>>>>>> 8bd5679f0915566d6e588b99e4c05e916e2e99f6
                ('NameA', models.TextField(max_length=2550, null=True)),
                ('NameL', models.TextField(max_length=2550)),
                ('Level', models.IntegerField()),
                ('ImageUrl', models.TextField(max_length=2550, null=True)),
<<<<<<< HEAD
                ('MainCategoryId', models.ForeignKey(db_column='MainCategoryId', db_constraint=False, default='null', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.categories')),
=======
                ('MainCategoryId', models.ForeignKey(db_column='MainCategoryId', db_constraint=False, default='null',
                 null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.categories')),
>>>>>>> 8bd5679f0915566d6e588b99e4c05e916e2e99f6
            ],
        ),
        migrations.CreateModel(
            name='countries',
            fields=[
<<<<<<< HEAD
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
=======
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
>>>>>>> 8bd5679f0915566d6e588b99e4c05e916e2e99f6
                ('NameA', models.TextField(max_length=2550, null=True)),
                ('NameL', models.TextField(max_length=2550)),
                ('Symbol', models.TextField(max_length=2550)),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
<<<<<<< HEAD
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
=======
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
>>>>>>> 8bd5679f0915566d6e588b99e4c05e916e2e99f6
                ('UnitPrice', models.FloatField()),
                ('TotalPrice', models.FloatField()),
                ('isDelivered', models.BooleanField()),
                ('Latitude', models.TextField(max_length=2550, null=True)),
                ('Longitude', models.TextField(max_length=2550, null=True)),
                ('Quantity', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='orderStatus',
            fields=[
<<<<<<< HEAD
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
=======
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
>>>>>>> 8bd5679f0915566d6e588b99e4c05e916e2e99f6
                ('Code', models.IntegerField()),
                ('StatusNameA', models.TextField(max_length=2550, null=True)),
                ('StatusNameL', models.TextField(max_length=2550)),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
<<<<<<< HEAD
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameA', models.TextField(max_length=2550, null=True)),
                ('NameL', models.TextField(max_length=2550)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='')),
                ('Image2', models.ImageField(blank=True, null=True, upload_to='')),
                ('Image3', models.ImageField(blank=True, null=True, upload_to='')),
                ('Image4', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('Description', models.TextField(max_length=2550, null=True)),
                ('BrandId', models.ForeignKey(db_column='BrandId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.brands')),
                ('CategoryId', models.ForeignKey(db_column='CategoryId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.categories')),
=======
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('NameA', models.TextField(max_length=2550, null=True)),
                ('NameL', models.TextField(max_length=2550)),
                ('Image', models.ImageField(blank=True, null=True)),
                ('Image2', models.ImageField(blank=True, null=True)),
                ('Image3', models.ImageField(blank=True, null=True)),
                ('Image4', models.ImageField(blank=True, null=True)),
                ('Description', models.TextField(max_length=2550, null=True)),
                ('BrandId', models.ForeignKey(db_column='BrandId', db_constraint=False,
                 on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.brands')),
                ('CategoryId', models.ForeignKey(db_column='CategoryId', db_constraint=False,
                 on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.categories')),
>>>>>>> 8bd5679f0915566d6e588b99e4c05e916e2e99f6
            ],
        ),
        migrations.CreateModel(
            name='shippingAgents',
            fields=[
<<<<<<< HEAD
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
=======
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
>>>>>>> 8bd5679f0915566d6e588b99e4c05e916e2e99f6
                ('NameA', models.TextField(max_length=2550, null=True)),
                ('NameL', models.TextField(max_length=2550)),
                ('Address1', models.TextField(max_length=2550)),
                ('Address2', models.TextField(max_length=2550, null=True)),
                ('Phone', models.TextField(max_length=2550, null=True)),
                ('Email', models.TextField(max_length=2550)),
                ('Password', models.TextField(max_length=2550)),
                ('PostCode', models.TextField(max_length=2550, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='specifications',
            fields=[
<<<<<<< HEAD
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
=======
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
>>>>>>> 8bd5679f0915566d6e588b99e4c05e916e2e99f6
                ('NameA', models.TextField(max_length=2550, null=True)),
                ('NameL', models.TextField(max_length=2550)),
                ('ShowInFilter', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='specificationValue',
            fields=[
<<<<<<< HEAD
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
=======
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
>>>>>>> 8bd5679f0915566d6e588b99e4c05e916e2e99f6
                ('Name', models.TextField(max_length=2550)),
            ],
        ),
        migrations.CreateModel(
            name='stores',
            fields=[
<<<<<<< HEAD
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
=======
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
>>>>>>> 8bd5679f0915566d6e588b99e4c05e916e2e99f6
                ('NameA', models.TextField(max_length=2550, null=True)),
                ('NameL', models.TextField(max_length=2550)),
                ('Email', models.TextField(max_length=2550)),
                ('Address', models.TextField(max_length=2550, null=True)),
                ('City', models.TextField(max_length=2550)),
                ('Latitude', models.TextField(max_length=2550, null=True)),
                ('Longitude', models.TextField(max_length=2550, null=True)),
<<<<<<< HEAD
                ('CountryId', models.ForeignKey(db_column='CountryId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.countries')),
                ('ShippingAgentId', models.ForeignKey(db_column='ShippingAgentId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.shippingagents')),
=======
                ('CountryId', models.ForeignKey(db_column='CountryId', db_constraint=False,
                 on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.countries')),
                ('ShippingAgentId', models.ForeignKey(db_column='ShippingAgentId', db_constraint=False,
                 on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.shippingagents')),
>>>>>>> 8bd5679f0915566d6e588b99e4c05e916e2e99f6
            ],
        ),
        migrations.CreateModel(
            name='transactionTypes',
            fields=[
<<<<<<< HEAD
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
=======
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
>>>>>>> 8bd5679f0915566d6e588b99e4c05e916e2e99f6
                ('Code', models.IntegerField()),
                ('NameA', models.TextField(max_length=2550, null=True)),
                ('NameL', models.TextField(max_length=2550)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
<<<<<<< HEAD
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
=======
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
>>>>>>> 8bd5679f0915566d6e588b99e4c05e916e2e99f6
                ('NameA', models.TextField(max_length=2550, null=True)),
                ('NameL', models.TextField(max_length=2550)),
                ('Email', models.TextField(max_length=2550)),
                ('Password', models.TextField(max_length=2550)),
                ('Address1', models.TextField(max_length=2550, null=True)),
                ('Address2', models.TextField(max_length=2550, null=True)),
                ('Phone', models.IntegerField(null=True)),
                ('City', models.TextField(max_length=2550, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='vendors',
            fields=[
<<<<<<< HEAD
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
=======
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
>>>>>>> 8bd5679f0915566d6e588b99e4c05e916e2e99f6
                ('NameA', models.TextField(max_length=2550, null=True)),
                ('NameL', models.TextField(max_length=2550)),
                ('Address1', models.TextField(max_length=2550)),
                ('Address2', models.TextField(max_length=2550, null=True)),
                ('Phone', models.TextField(max_length=2550, null=True)),
                ('Email', models.TextField(max_length=2550)),
                ('Password', models.TextField(max_length=2550)),
                ('PostCode', models.TextField(max_length=2550, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='vendorPriceLists',
            fields=[
<<<<<<< HEAD
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Price', models.FloatField()),
                ('CountryId', models.ForeignKey(db_column='CountryId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.countries')),
                ('ProductId', models.ForeignKey(db_column='ProductId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.products')),
                ('VendorId', models.ForeignKey(db_column='VendorId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.vendors')),
=======
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('Price', models.FloatField()),
                ('CountryId', models.ForeignKey(db_column='CountryId', db_constraint=False,
                 on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.countries')),
                ('ProductId', models.ForeignKey(db_column='ProductId', db_constraint=False,
                 on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.products')),
                ('VendorId', models.ForeignKey(db_column='VendorId', db_constraint=False,
                 on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.vendors')),
>>>>>>> 8bd5679f0915566d6e588b99e4c05e916e2e99f6
            ],
        ),
        migrations.CreateModel(
            name='storeShippingAgents',
            fields=[
<<<<<<< HEAD
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ShippingAgentId', models.ForeignKey(db_column='ShippingAgentId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.shippingagents')),
                ('StoreId', models.ForeignKey(db_column='StoreId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.stores')),
=======
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('ShippingAgentId', models.ForeignKey(db_column='ShippingAgentId', db_constraint=False,
                 on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.shippingagents')),
                ('StoreId', models.ForeignKey(db_column='StoreId', db_constraint=False,
                 on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.stores')),
>>>>>>> 8bd5679f0915566d6e588b99e4c05e916e2e99f6
            ],
        ),
        migrations.AddField(
            model_name='stores',
            name='VendorId',
<<<<<<< HEAD
            field=models.ForeignKey(db_column='VendorId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.vendors'),
=======
            field=models.ForeignKey(db_column='VendorId', db_constraint=False,
                                    on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.vendors'),
>>>>>>> 8bd5679f0915566d6e588b99e4c05e916e2e99f6
        ),
        migrations.CreateModel(
            name='shippingDetails',
            fields=[
<<<<<<< HEAD
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DeliveryNotes', models.TextField(max_length=2550, null=True)),
                ('OrderId', models.ForeignKey(db_column='OrderId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.orders')),
                ('ShippingAgentId', models.ForeignKey(db_column='ShippingAgentId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.shippingagents')),
=======
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('DeliveryNotes', models.TextField(max_length=2550, null=True)),
                ('OrderId', models.ForeignKey(db_column='OrderId', db_constraint=False,
                 on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.orders')),
                ('ShippingAgentId', models.ForeignKey(db_column='ShippingAgentId', db_constraint=False,
                 on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.shippingagents')),
>>>>>>> 8bd5679f0915566d6e588b99e4c05e916e2e99f6
            ],
        ),
        migrations.CreateModel(
            name='shippingAgentUsers',
            fields=[
<<<<<<< HEAD
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ShippingAgentId', models.ForeignKey(db_column='ShippingAgentId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.shippingagents')),
                ('UserId', models.ForeignKey(db_column='UserId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.users')),
=======
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('ShippingAgentId', models.ForeignKey(db_column='ShippingAgentId', db_constraint=False,
                 on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.shippingagents')),
                ('UserId', models.ForeignKey(db_column='UserId', db_constraint=False,
                 on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.users')),
>>>>>>> 8bd5679f0915566d6e588b99e4c05e916e2e99f6
            ],
        ),
        migrations.CreateModel(
            name='productStoreRatings',
            fields=[
<<<<<<< HEAD
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RatingId', models.IntegerField()),
                ('ProductReview', models.TextField(max_length=2550, null=True)),
                ('ProductId', models.ForeignKey(db_column='ProductId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.products')),
                ('StoreId', models.ForeignKey(db_column='StoreId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.stores')),
                ('UserId', models.ForeignKey(db_column='UserId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.users')),
=======
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('RatingId', models.IntegerField()),
                ('ProductReview', models.TextField(max_length=2550, null=True)),
                ('ProductId', models.ForeignKey(db_column='ProductId', db_constraint=False,
                 on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.products')),
                ('StoreId', models.ForeignKey(db_column='StoreId', db_constraint=False,
                 on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.stores')),
                ('UserId', models.ForeignKey(db_column='UserId', db_constraint=False,
                 on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.users')),
>>>>>>> 8bd5679f0915566d6e588b99e4c05e916e2e99f6
            ],
        ),
        migrations.CreateModel(
            name='productSpecifications',
            fields=[
<<<<<<< HEAD
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SpecificationName', models.TextField(max_length=2550)),
                ('SpecificationValue', models.TextField(max_length=2550)),
                ('ShowInFilter', models.BooleanField(null=True)),
                ('CategoryId', models.ForeignKey(db_column='CategoryId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.categories')),
                ('ProductId', models.ForeignKey(db_column='ProductId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.products')),
                ('SpecificationId', models.ForeignKey(db_column='SpecificationId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.specifications')),
=======
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('SpecificationName', models.TextField(max_length=2550)),
                ('SpecificationValue', models.TextField(max_length=2550)),
                ('ShowInFilter', models.BooleanField(null=True)),
                ('CategoryId', models.ForeignKey(db_column='CategoryId', db_constraint=False,
                 on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.categories')),
                ('ProductId', models.ForeignKey(db_column='ProductId', db_constraint=False,
                 on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.products')),
                ('SpecificationId', models.ForeignKey(db_column='SpecificationId', db_constraint=False,
                 on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.specifications')),
>>>>>>> 8bd5679f0915566d6e588b99e4c05e916e2e99f6
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='DeliveredByUserId',
<<<<<<< HEAD
            field=models.ForeignKey(db_column='DeliveredByUserId', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='UserId', to='PyCommerce.users'),
=======
            field=models.ForeignKey(db_column='DeliveredByUserId', db_constraint=False, null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING, related_name='UserId', to='PyCommerce.users'),
>>>>>>> 8bd5679f0915566d6e588b99e4c05e916e2e99f6
        ),
        migrations.AddField(
            model_name='orders',
            name='MasterId',
<<<<<<< HEAD
            field=models.ForeignKey(db_column='MasterId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.carttransactionmasters'),
=======
            field=models.ForeignKey(db_column='MasterId', db_constraint=False,
                                    on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.carttransactionmasters'),
>>>>>>> 8bd5679f0915566d6e588b99e4c05e916e2e99f6
        ),
        migrations.AddField(
            model_name='orders',
            name='ProductId',
<<<<<<< HEAD
            field=models.ForeignKey(db_column='ProductId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.products'),
=======
            field=models.ForeignKey(db_column='ProductId', db_constraint=False,
                                    on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.products'),
>>>>>>> 8bd5679f0915566d6e588b99e4c05e916e2e99f6
        ),
        migrations.AddField(
            model_name='orders',
            name='ShippingAgentId',
<<<<<<< HEAD
            field=models.ForeignKey(db_column='ShippingAgentId', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.shippingagents'),
=======
            field=models.ForeignKey(db_column='ShippingAgentId', db_constraint=False, null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.shippingagents'),
>>>>>>> 8bd5679f0915566d6e588b99e4c05e916e2e99f6
        ),
        migrations.AddField(
            model_name='orders',
            name='StoreId',
<<<<<<< HEAD
            field=models.ForeignKey(db_column='StoreId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.stores'),
=======
            field=models.ForeignKey(db_column='StoreId', db_constraint=False,
                                    on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.stores'),
>>>>>>> 8bd5679f0915566d6e588b99e4c05e916e2e99f6
        ),
        migrations.AddField(
            model_name='orders',
            name='UserId',
<<<<<<< HEAD
            field=models.ForeignKey(db_column='UserId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.users'),
=======
            field=models.ForeignKey(db_column='UserId', db_constraint=False,
                                    on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.users'),
>>>>>>> 8bd5679f0915566d6e588b99e4c05e916e2e99f6
        ),
        migrations.AddField(
            model_name='orders',
            name='cartId',
<<<<<<< HEAD
            field=models.ForeignKey(db_column='CartId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.carttransactions'),
=======
            field=models.ForeignKey(db_column='CartId', db_constraint=False,
                                    on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.carttransactions'),
>>>>>>> 8bd5679f0915566d6e588b99e4c05e916e2e99f6
        ),
        migrations.CreateModel(
            name='orderMasters',
            fields=[
<<<<<<< HEAD
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateCreated', models.DateTimeField()),
                ('ShippingAddress', models.TextField(max_length=2550, null=True)),
                ('OrderStatusId', models.ForeignKey(db_column='OrderStatusId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.orderstatus')),
                ('UserId', models.ForeignKey(db_column='UserId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.users')),
                ('cartId', models.ForeignKey(db_column='CartId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.carttransactions')),
=======
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('DateCreated', models.DateTimeField()),
                ('ShippingAddress', models.TextField(max_length=2550, null=True)),
                ('OrderStatusId', models.ForeignKey(db_column='OrderStatusId', db_constraint=False,
                 on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.orderstatus')),
                ('UserId', models.ForeignKey(db_column='UserId', db_constraint=False,
                 on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.users')),
                ('cartId', models.ForeignKey(db_column='CartId', db_constraint=False,
                 on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.carttransactions')),
>>>>>>> 8bd5679f0915566d6e588b99e4c05e916e2e99f6
            ],
        ),
        migrations.CreateModel(
            name='inventoryDetails',
            fields=[
<<<<<<< HEAD
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.FloatField()),
                ('ProductId', models.ForeignKey(db_column='ProductId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.products')),
                ('StoreId', models.ForeignKey(db_column='StoreId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.stores')),
=======
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.FloatField()),
                ('ProductId', models.ForeignKey(db_column='ProductId', db_constraint=False,
                 on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.products')),
                ('StoreId', models.ForeignKey(db_column='StoreId', db_constraint=False,
                 on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.stores')),
>>>>>>> 8bd5679f0915566d6e588b99e4c05e916e2e99f6
            ],
        ),
        migrations.CreateModel(
            name='inventoryBalances',
            fields=[
<<<<<<< HEAD
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuantityBalance', models.FloatField()),
                ('ProductId', models.ForeignKey(db_column='ProductId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.products')),
                ('StoreId', models.ForeignKey(db_column='StoreId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.stores')),
=======
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('QuantityBalance', models.FloatField()),
                ('ProductId', models.ForeignKey(db_column='ProductId', db_constraint=False,
                 on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.products')),
                ('StoreId', models.ForeignKey(db_column='StoreId', db_constraint=False,
                 on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.stores')),
>>>>>>> 8bd5679f0915566d6e588b99e4c05e916e2e99f6
            ],
        ),
        migrations.AddField(
            model_name='carttransactions',
            name='ProductId',
<<<<<<< HEAD
            field=models.ForeignKey(db_column='ProductId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.products'),
=======
            field=models.ForeignKey(db_column='ProductId', db_constraint=False,
                                    on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.products'),
>>>>>>> 8bd5679f0915566d6e588b99e4c05e916e2e99f6
        ),
        migrations.AddField(
            model_name='carttransactions',
            name='StoreId',
<<<<<<< HEAD
            field=models.ForeignKey(db_column='StoreId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.stores'),
=======
            field=models.ForeignKey(db_column='StoreId', db_constraint=False,
                                    on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.stores'),
>>>>>>> 8bd5679f0915566d6e588b99e4c05e916e2e99f6
        ),
    ]
