# Generated by Django 3.1.7 on 2021-04-03 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GetHomeProducts',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('StoreId', models.IntegerField()),
                ('ProductId', models.IntegerField()),
                ('QuantityBalance', models.FloatField()),
                ('ProductName', models.CharField(max_length=2550)),
                ('StoreName', models.CharField(max_length=2550)),
                ('ImageUrl', models.CharField(max_length=2550)),
                ('ImageUrl6', models.CharField(max_length=2550)),
                ('ImageUrl7', models.CharField(max_length=2550)),
                ('Description', models.CharField(max_length=2550)),
                ('Price', models.FloatField()),
                ('Currency', models.CharField(max_length=2550)),
                ('CategoryId', models.IntegerField()),
                ('PageNumber', models.IntegerField()),
                ('FiveStarsCount', models.FloatField()),
                ('FourStarsCount', models.FloatField()),
                ('ThreeStarsCount', models.FloatField()),
                ('TwoStarsCount', models.FloatField()),
                ('OneStarsCount', models.FloatField()),
                ('MaxTotalRating', models.FloatField()),
                ('finalProductRating', models.FloatField()),
                ('OutOfFivestring', models.FloatField()),
            ],
            options={
                'db_table': 'GetHomeProducts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('NameA', models.CharField(max_length=2550)),
                ('NameL', models.CharField(max_length=2550)),
            ],
        ),
        migrations.CreateModel(
            name='CartTransaction',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('ProductId', models.IntegerField()),
                ('MasterId', models.IntegerField()),
                ('StoreId', models.IntegerField()),
                ('Quantity', models.FloatField()),
                ('IsOrdered', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CartTransactionMaster',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('DateCreated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('MainCategoryId', models.IntegerField()),
                ('NameA', models.CharField(max_length=2550)),
                ('NameL', models.CharField(max_length=2550)),
                ('Level', models.IntegerField()),
                ('ImageUrl', models.CharField(max_length=2550)),
            ],
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('NameA', models.CharField(max_length=2550)),
                ('NameL', models.CharField(max_length=2550)),
                ('Symbol', models.CharField(max_length=2550)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryBalance',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('StoreId', models.IntegerField()),
                ('ProductId', models.IntegerField()),
                ('QuantityBalance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='InventoryDetail',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('TransType', models.IntegerField()),
                ('TransDate', models.DateField()),
                ('StoreId', models.IntegerField()),
                ('ProductId', models.IntegerField()),
                ('Quantity', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderMaster',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('cartId', models.IntegerField()),
                ('UserId', models.IntegerField()),
                ('DateCreated', models.DateTimeField()),
                ('ShippingAdress', models.CharField(max_length=2550)),
                ('OrderStatusId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('ProductId', models.IntegerField()),
                ('StoreId', models.IntegerField()),
                ('cartId', models.IntegerField()),
                ('MasterId', models.IntegerField()),
                ('UserId', models.IntegerField()),
                ('Quantity', models.FloatField()),
                ('ShippingAgentId', models.IntegerField()),
                ('UnitPrice', models.FloatField()),
                ('TotalPrice', models.FloatField()),
                ('isDelivered', models.IntegerField()),
                ('MapLocation', models.CharField(max_length=2550)),
                ('DeliveredByUserId', models.IntegerField()),
                ('Latitude', models.CharField(max_length=2550)),
                ('Longitude', models.CharField(max_length=2550)),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Code', models.IntegerField()),
                ('StatusNameA', models.CharField(max_length=2550)),
                ('StatusNameL', models.CharField(max_length=2550)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('NameA', models.CharField(max_length=2550)),
                ('NameL', models.CharField(max_length=2550)),
                ('ImageUrl', models.CharField(max_length=2550)),
                ('ImageUrl6', models.CharField(max_length=2550)),
                ('ImageUrl7', models.CharField(max_length=2550)),
                ('CategoryId', models.IntegerField()),
                ('BrandId', models.IntegerField()),
                ('Description', models.CharField(max_length=2550)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSpecifications',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('CategoryId', models.IntegerField()),
                ('ProductId', models.IntegerField()),
                ('SpecificationId', models.IntegerField()),
                ('SpecificationName', models.CharField(max_length=2550)),
                ('SpecificationValue', models.CharField(max_length=2550)),
                ('ShowInFilter', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductStoreRating',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('ProductId', models.IntegerField()),
                ('StoreId', models.IntegerField()),
                ('UserId', models.IntegerField()),
                ('RatingId', models.IntegerField()),
                ('ProductReview', models.CharField(max_length=2550)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAgent',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('NameA', models.CharField(max_length=2550)),
                ('NameL', models.CharField(max_length=2550)),
                ('Adress1', models.CharField(max_length=2550)),
                ('Adress2', models.CharField(max_length=2550)),
                ('Phone', models.CharField(max_length=2550)),
                ('Email', models.CharField(max_length=2550)),
                ('Password', models.CharField(max_length=2550)),
                ('PostCode', models.CharField(max_length=2550)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAgentUser',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('UserId', models.IntegerField()),
                ('ShippingAgentId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ShippingDetails',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('ShippingAgentId', models.IntegerField()),
                ('OrderId', models.IntegerField()),
                ('DeliveryNotes', models.CharField(max_length=2550)),
            ],
        ),
        migrations.CreateModel(
            name='Specifications',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('NameA', models.CharField(max_length=2550)),
                ('NameL', models.CharField(max_length=2550)),
                ('ShowInFilter', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SpecificationValueCounts',
            fields=[
                ('SpecificationValue', models.CharField(max_length=2550, primary_key=True, serialize=False)),
                ('SpecificationCount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('VendorId', models.IntegerField()),
                ('NameA', models.CharField(max_length=2550)),
                ('NameL', models.CharField(max_length=2550)),
                ('email', models.CharField(max_length=2550)),
                ('Address', models.CharField(max_length=2550)),
                ('CountryId', models.IntegerField()),
                ('City', models.CharField(max_length=2550)),
                ('MapLocation', models.CharField(max_length=2550)),
                ('ShippingAgentId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StoreShippingAgent',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('StoreId', models.IntegerField()),
                ('ShippingAgentId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Code', models.IntegerField()),
                ('NameA', models.CharField(max_length=2550)),
                ('NameL', models.CharField(max_length=2550)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('NameA', models.CharField(max_length=2550)),
                ('NameL', models.CharField(max_length=2550)),
                ('Email', models.CharField(max_length=2550)),
                ('Password', models.CharField(max_length=2550)),
                ('City', models.CharField(max_length=2550)),
            ],
        ),
        migrations.CreateModel(
            name='VendorPriceList',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('VendorId', models.IntegerField()),
                ('ProductId', models.IntegerField()),
                ('CountryId', models.IntegerField()),
                ('Price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Vendors',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('NameA', models.CharField(max_length=2550)),
                ('NameL', models.CharField(max_length=2550)),
                ('Adress1', models.CharField(max_length=2550)),
                ('Adress2', models.CharField(max_length=2550)),
                ('Phone', models.CharField(max_length=2550)),
                ('Email', models.CharField(max_length=2550)),
                ('Password', models.CharField(max_length=2550)),
                ('PostCode', models.CharField(max_length=2550)),
            ],
        ),
    ]
