# Generated by Django 3.2.4 on 2021-06-13 15:58

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='getHomeProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuantityBalance', models.FloatField()),
                ('ProductName', models.CharField(max_length=2550)),
                ('StoreName', models.CharField(max_length=2550)),
                ('Image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=100, size=[300, 200], upload_to='')),
                ('Image2', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=100, size=[300, 200], upload_to='')),
                ('Image3', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=100, size=[300, 200], upload_to='')),
                ('Image4', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=100, size=[300, 200], upload_to='')),
                ('Description', models.CharField(max_length=2550)),
                ('Price', models.FloatField()),
                ('Currency', models.CharField(max_length=2550)),
                ('PageNumber', models.IntegerField()),
                ('FiveStarsCount', models.FloatField()),
                ('FourStarsCount', models.FloatField()),
                ('ThreeStarsCount', models.FloatField()),
                ('TwoStarsCount', models.FloatField()),
                ('OneStarsCount', models.FloatField()),
                ('MaxTotalRating', models.FloatField()),
                ('finalProductRating', models.FloatField()),
                ('OutOfFivestring', models.FloatField()),
            ],
            options={
                'db_table': 'GetHomeProducts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='specificationValueCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SpecificationId', models.IntegerField()),
                ('SpecificationValue', models.CharField(max_length=2550)),
                ('SpecificationCount', models.IntegerField()),
                ('CategoryId', models.IntegerField()),
            ],
            options={
                'db_table': 'SpecificationValueCount',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='starPercent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FiveStarsCount', models.FloatField()),
                ('FourStarsCount', models.FloatField()),
                ('ThreeStarsCount', models.FloatField()),
                ('TwoStarsCount', models.FloatField()),
                ('OneStarCount', models.FloatField()),
                ('FiveStarsPercent', models.FloatField()),
                ('FourStarsPercent', models.FloatField()),
                ('ThreeStarsPercent', models.FloatField()),
                ('TwoStarsPercent', models.FloatField()),
                ('OneStarPercent', models.FloatField()),
                ('averageRating', models.FloatField()),
                ('OutOfFive', models.FloatField()),
                ('allReviewsCount', models.IntegerField()),
            ],
            options={
                'db_table': 'GetStarPercent',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='brands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameA', models.CharField(max_length=2550, null=True)),
                ('NameL', models.CharField(max_length=2550)),
            ],
        ),
        migrations.CreateModel(
            name='cartTransactionMasters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateCreated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='cartTransactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.FloatField()),
                ('IsOrdered', models.IntegerField()),
                ('MasterId', models.ForeignKey(db_column='MasterId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.carttransactionmasters')),
            ],
        ),
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameA', models.CharField(max_length=2550, null=True)),
                ('NameL', models.CharField(max_length=2550)),
                ('Level', models.IntegerField()),
                ('ImageUrl', models.CharField(max_length=2550, null=True)),
                ('MainCategoryId', models.ForeignKey(db_column='MainCategoryId', db_constraint=False, default='null', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.categories')),
            ],
        ),
        migrations.CreateModel(
            name='countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameA', models.CharField(max_length=2550, null=True)),
                ('NameL', models.CharField(max_length=2550)),
                ('Symbol', models.CharField(max_length=2550)),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UnitPrice', models.FloatField()),
                ('TotalPrice', models.FloatField()),
                ('isDelivered', models.BooleanField()),
                ('Latitude', models.CharField(max_length=2550, null=True)),
                ('Longitude', models.CharField(max_length=2550, null=True)),
                ('Quantity', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='orderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.IntegerField()),
                ('StatusNameA', models.CharField(max_length=2550, null=True)),
                ('StatusNameL', models.CharField(max_length=2550)),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameA', models.CharField(max_length=2550, null=True)),
                ('NameL', models.CharField(max_length=2550)),
                ('Image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=100, size=[300, 200], upload_to='')),
                ('Image2', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=100, size=[300, 200], upload_to='')),
                ('Image3', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=100, size=[300, 200], upload_to='')),
                ('Image4', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=100, size=[300, 200], upload_to='')),
                ('Description', models.CharField(max_length=2550, null=True)),
                ('BrandId', models.ForeignKey(db_column='BrandId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.brands')),
                ('CategoryId', models.ForeignKey(db_column='CategoryId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.categories')),
            ],
        ),
        migrations.CreateModel(
            name='shippingAgents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameA', models.CharField(max_length=2550, null=True)),
                ('NameL', models.CharField(max_length=2550)),
                ('Address1', models.CharField(max_length=2550)),
                ('Address2', models.CharField(max_length=2550, null=True)),
                ('Phone', models.CharField(max_length=2550, null=True)),
                ('Email', models.CharField(max_length=2550)),
                ('Password', models.CharField(max_length=2550)),
                ('PostCode', models.CharField(max_length=2550, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='specifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameA', models.CharField(max_length=2550, null=True)),
                ('NameL', models.CharField(max_length=2550)),
                ('ShowInFilter', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='specificationValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=2550)),
            ],
        ),
        migrations.CreateModel(
            name='stores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameA', models.CharField(max_length=2550, null=True)),
                ('NameL', models.CharField(max_length=2550)),
                ('Email', models.CharField(max_length=2550)),
                ('Address', models.CharField(max_length=2550, null=True)),
                ('City', models.CharField(max_length=2550)),
                ('Latitude', models.CharField(max_length=2550, null=True)),
                ('Longitude', models.CharField(max_length=2550, null=True)),
                ('CountryId', models.ForeignKey(db_column='CountryId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.countries')),
                ('ShippingAgentId', models.ForeignKey(db_column='ShippingAgentId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.shippingagents')),
            ],
        ),
        migrations.CreateModel(
            name='transactionTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.IntegerField()),
                ('NameA', models.CharField(max_length=2550, null=True)),
                ('NameL', models.CharField(max_length=2550)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameA', models.CharField(max_length=2550, null=True)),
                ('NameL', models.CharField(max_length=2550)),
                ('Email', models.CharField(max_length=2550)),
                ('Password', models.CharField(max_length=2550)),
                ('Address1', models.CharField(max_length=2550, null=True)),
                ('Address2', models.CharField(max_length=2550, null=True)),
                ('Phone', models.IntegerField(null=True)),
                ('City', models.CharField(max_length=2550, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='vendors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameA', models.CharField(max_length=2550, null=True)),
                ('NameL', models.CharField(max_length=2550)),
                ('Address1', models.CharField(max_length=2550)),
                ('Address2', models.CharField(max_length=2550, null=True)),
                ('Phone', models.CharField(max_length=2550, null=True)),
                ('Email', models.CharField(max_length=2550)),
                ('Password', models.CharField(max_length=2550)),
                ('PostCode', models.CharField(max_length=2550, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='vendorPriceLists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Price', models.FloatField()),
                ('CountryId', models.ForeignKey(db_column='CountryId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.countries')),
                ('ProductId', models.ForeignKey(db_column='ProductId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.products')),
                ('VendorId', models.ForeignKey(db_column='VendorId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.vendors')),
            ],
        ),
        migrations.CreateModel(
            name='storeShippingAgents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ShippingAgentId', models.ForeignKey(db_column='ShippingAgentId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.shippingagents')),
                ('StoreId', models.ForeignKey(db_column='StoreId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.stores')),
            ],
        ),
        migrations.AddField(
            model_name='stores',
            name='VendorId',
            field=models.ForeignKey(db_column='VendorId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.vendors'),
        ),
        migrations.CreateModel(
            name='shippingDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DeliveryNotes', models.CharField(max_length=2550, null=True)),
                ('OrderId', models.ForeignKey(db_column='OrderId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.orders')),
                ('ShippingAgentId', models.ForeignKey(db_column='ShippingAgentId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.shippingagents')),
            ],
        ),
        migrations.CreateModel(
            name='shippingAgentUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ShippingAgentId', models.ForeignKey(db_column='ShippingAgentId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.shippingagents')),
                ('UserId', models.ForeignKey(db_column='UserId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.users')),
            ],
        ),
        migrations.CreateModel(
            name='productStoreRatings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RatingId', models.IntegerField()),
                ('ProductReview', models.CharField(max_length=2550, null=True)),
                ('ProductId', models.ForeignKey(db_column='ProductId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.products')),
                ('StoreId', models.ForeignKey(db_column='StoreId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.stores')),
                ('UserId', models.ForeignKey(db_column='UserId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.users')),
            ],
        ),
        migrations.CreateModel(
            name='productSpecifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SpecificationName', models.CharField(max_length=2550)),
                ('SpecificationValue', models.CharField(max_length=2550)),
                ('ShowInFilter', models.BooleanField(null=True)),
                ('CategoryId', models.ForeignKey(db_column='CategoryId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.categories')),
                ('ProductId', models.ForeignKey(db_column='ProductId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.products')),
                ('SpecificationId', models.ForeignKey(db_column='SpecificationId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.specifications')),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='DeliveredByUserId',
            field=models.ForeignKey(db_column='DeliveredByUserId', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='UserId', to='PyCommerce.users'),
        ),
        migrations.AddField(
            model_name='orders',
            name='MasterId',
            field=models.ForeignKey(db_column='MasterId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.carttransactionmasters'),
        ),
        migrations.AddField(
            model_name='orders',
            name='ProductId',
            field=models.ForeignKey(db_column='ProductId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.products'),
        ),
        migrations.AddField(
            model_name='orders',
            name='ShippingAgentId',
            field=models.ForeignKey(db_column='ShippingAgentId', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.shippingagents'),
        ),
        migrations.AddField(
            model_name='orders',
            name='StoreId',
            field=models.ForeignKey(db_column='StoreId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.stores'),
        ),
        migrations.AddField(
            model_name='orders',
            name='UserId',
            field=models.ForeignKey(db_column='UserId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.users'),
        ),
        migrations.AddField(
            model_name='orders',
            name='cartId',
            field=models.ForeignKey(db_column='CartId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.carttransactions'),
        ),
        migrations.CreateModel(
            name='orderMasters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateCreated', models.DateTimeField()),
                ('ShippingAddress', models.CharField(max_length=2550, null=True)),
                ('OrderStatusId', models.ForeignKey(db_column='OrderStatusId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.orderstatus')),
                ('UserId', models.ForeignKey(db_column='UserId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.users')),
                ('cartId', models.ForeignKey(db_column='CartId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.carttransactions')),
            ],
        ),
        migrations.CreateModel(
            name='inventoryDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.FloatField()),
                ('ProductId', models.ForeignKey(db_column='ProductId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.products')),
                ('StoreId', models.ForeignKey(db_column='StoreId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.stores')),
            ],
        ),
        migrations.CreateModel(
            name='inventoryBalances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuantityBalance', models.FloatField()),
                ('ProductId', models.ForeignKey(db_column='ProductId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.products')),
                ('StoreId', models.ForeignKey(db_column='StoreId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.stores')),
            ],
        ),
        migrations.AddField(
            model_name='carttransactions',
            name='ProductId',
            field=models.ForeignKey(db_column='ProductId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.products'),
        ),
        migrations.AddField(
            model_name='carttransactions',
            name='StoreId',
            field=models.ForeignKey(db_column='StoreId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.stores'),
        ),
    ]
