<<<<<<< HEAD
# Generated by Django 3.2.5 on 2021-07-08 18:00
=======
# Generated by Django 3.2.4 on 2021-06-16 22:05
>>>>>>> 8bd5679f0915566d6e588b99e4c05e916e2e99f6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PyCommerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='getHomeProducts',
            fields=[
<<<<<<< HEAD
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuantityBalance', models.FloatField()),
                ('ProductName', models.TextField(max_length=2550)),
                ('StoreName', models.TextField(max_length=2550)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='')),
                ('Image2', models.ImageField(blank=True, null=True, upload_to='')),
                ('Image3', models.ImageField(blank=True, null=True, upload_to='')),
                ('Image4', models.ImageField(blank=True, null=True, upload_to='')),
=======
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('QuantityBalance', models.FloatField()),
                ('ProductName', models.TextField(max_length=2550)),
                ('StoreName', models.TextField(max_length=2550)),
                ('Image', models.ImageField(blank=True, null=True)),
                ('Image2', models.ImageField(blank=True, null=True)),
                ('Image3', models.ImageField(blank=True, null=True)),
                ('Image4', models.ImageField(blank=True, null=True)),
>>>>>>> 8bd5679f0915566d6e588b99e4c05e916e2e99f6
                ('Description', models.TextField(max_length=2550)),
                ('Price', models.FloatField()),
                ('Currency', models.TextField(max_length=2550)),
                ('PageNumber', models.IntegerField()),
                ('FiveStarsCount', models.FloatField()),
                ('FourStarsCount', models.FloatField()),
                ('ThreeStarsCount', models.FloatField()),
                ('TwoStarsCount', models.FloatField()),
                ('OneStarsCount', models.FloatField()),
                ('MaxTotalRating', models.FloatField()),
                ('finalProductRating', models.FloatField()),
                ('OutOfFivestring', models.FloatField()),
            ],
            options={
<<<<<<< HEAD
                'db_table': 'gethomeproducts',
=======
                'db_table': 'GetHomeProducts',
>>>>>>> 8bd5679f0915566d6e588b99e4c05e916e2e99f6
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='specificationValueCount',
            fields=[
<<<<<<< HEAD
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
=======
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
>>>>>>> 8bd5679f0915566d6e588b99e4c05e916e2e99f6
                ('SpecificationId', models.IntegerField()),
                ('SpecificationValue', models.TextField(max_length=2550)),
                ('SpecificationCount', models.IntegerField()),
                ('CategoryId', models.IntegerField()),
            ],
            options={
<<<<<<< HEAD
                'db_table': 'specificationvaluecount',
=======
                'db_table': 'SpecificationValueCount',
>>>>>>> 8bd5679f0915566d6e588b99e4c05e916e2e99f6
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='starPercent',
            fields=[
<<<<<<< HEAD
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
=======
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
>>>>>>> 8bd5679f0915566d6e588b99e4c05e916e2e99f6
                ('FiveStarsCount', models.FloatField()),
                ('FourStarsCount', models.FloatField()),
                ('ThreeStarsCount', models.FloatField()),
                ('TwoStarsCount', models.FloatField()),
                ('OneStarCount', models.FloatField()),
                ('FiveStarsPercent', models.FloatField()),
                ('FourStarsPercent', models.FloatField()),
                ('ThreeStarsPercent', models.FloatField()),
                ('TwoStarsPercent', models.FloatField()),
                ('OneStarPercent', models.FloatField()),
                ('averageRating', models.FloatField()),
                ('OutOfFive', models.FloatField()),
                ('allReviewsCount', models.IntegerField()),
            ],
            options={
<<<<<<< HEAD
                'db_table': 'getstarpercent',
=======
                'db_table': 'GetStarPercent',
>>>>>>> 8bd5679f0915566d6e588b99e4c05e916e2e99f6
                'managed': False,
            },
        ),
    ]
