# Generated by Django 3.2.3 on 2021-05-20 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PyCommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carttransactions',
            name='MasterId',
            field=models.ForeignKey(db_column='MasterId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.ordermasters'),
        ),
        migrations.AlterField(
            model_name='carttransactions',
            name='ProductId',
            field=models.ForeignKey(db_column='ProductId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.products'),
        ),
        migrations.AlterField(
            model_name='carttransactions',
            name='StoreId',
            field=models.ForeignKey(db_column='StoreId', db_constraint=False, default=17, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.stores'),
        ),
        migrations.AlterField(
            model_name='inventorybalances',
            name='ProductId',
            field=models.ForeignKey(db_column='ProductId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.products'),
        ),
        migrations.AlterField(
            model_name='inventorybalances',
            name='StoreId',
            field=models.ForeignKey(db_column='StoreId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.stores'),
        ),
        migrations.AlterField(
            model_name='inventorydetails',
            name='ProductId',
            field=models.ForeignKey(db_column='ProductId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.products'),
        ),
        migrations.AlterField(
            model_name='inventorydetails',
            name='StoreId',
            field=models.ForeignKey(db_column='StoreId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.stores'),
        ),
        migrations.AlterField(
            model_name='ordermasters',
            name='OrderStatusId',
            field=models.ForeignKey(db_column='OrderStatusId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.orderstatus'),
        ),
        migrations.AlterField(
            model_name='ordermasters',
            name='UserId',
            field=models.ForeignKey(db_column='UserId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.users'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='ProductId',
            field=models.ForeignKey(db_column='ProductId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.products'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='ShippingAgentId',
            field=models.ForeignKey(db_column='ShippingAgentId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.shippingagents'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='StoreId',
            field=models.ForeignKey(db_column='StoreId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.stores'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='UserId',
            field=models.ForeignKey(db_column='UserId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.users'),
        ),
        migrations.AlterField(
            model_name='products',
            name='BrandId',
            field=models.ForeignKey(db_column='BrandId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.brands'),
        ),
        migrations.AlterField(
            model_name='products',
            name='CategoryId',
            field=models.ForeignKey(db_column='CategoryId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.categories'),
        ),
        migrations.AlterField(
            model_name='productspecifications',
            name='CategoryId',
            field=models.ForeignKey(db_column='CategoryId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.categories'),
        ),
        migrations.AlterField(
            model_name='productspecifications',
            name='ProductId',
            field=models.ForeignKey(db_column='ProductId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.products'),
        ),
        migrations.AlterField(
            model_name='productspecifications',
            name='SpecificationId',
            field=models.ForeignKey(db_column='SpecificationId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.specifications'),
        ),
        migrations.AlterField(
            model_name='productstoreratings',
            name='ProductId',
            field=models.ForeignKey(db_column='ProductId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.products'),
        ),
        migrations.AlterField(
            model_name='productstoreratings',
            name='StoreId',
            field=models.ForeignKey(db_column='StoreId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.stores'),
        ),
        migrations.AlterField(
            model_name='productstoreratings',
            name='UserId',
            field=models.ForeignKey(db_column='UserId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.users'),
        ),
        migrations.AlterField(
            model_name='shippingagentusers',
            name='ShippingAgentId',
            field=models.ForeignKey(db_column='ShippingAgentId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.shippingagents'),
        ),
        migrations.AlterField(
            model_name='shippingdetails',
            name='OrderId',
            field=models.ForeignKey(db_column='OrderId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.orders'),
        ),
        migrations.AlterField(
            model_name='shippingdetails',
            name='ShippingAgentId',
            field=models.ForeignKey(db_column='ShippingAgentId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.shippingagents'),
        ),
        migrations.AlterField(
            model_name='stores',
            name='CountryId',
            field=models.ForeignKey(db_column='CountryId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.countries'),
        ),
        migrations.AlterField(
            model_name='stores',
            name='ShippingAgentId',
            field=models.ForeignKey(db_column='ShippingAgentId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.shippingagents'),
        ),
        migrations.AlterField(
            model_name='stores',
            name='VendorId',
            field=models.ForeignKey(db_column='VendorId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.vendors'),
        ),
        migrations.AlterField(
            model_name='storeshippingagents',
            name='ShippingAgentId',
            field=models.ForeignKey(db_column='ShippingAgentId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.shippingagents'),
        ),
        migrations.AlterField(
            model_name='storeshippingagents',
            name='StoreId',
            field=models.ForeignKey(db_column='StoreId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.stores'),
        ),
        migrations.AlterField(
            model_name='vendorpricelists',
            name='CountryId',
            field=models.ForeignKey(db_column='CountryId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.countries'),
        ),
        migrations.AlterField(
            model_name='vendorpricelists',
            name='ProductId',
            field=models.ForeignKey(db_column='ProductId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.products'),
        ),
        migrations.AlterField(
            model_name='vendorpricelists',
            name='VendorId',
            field=models.ForeignKey(db_column='VendorId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.vendors'),
        ),
    ]
