# Generated by Django 3.2 on 2021-05-18 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PyCommerce', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartTransactionMaster',
            new_name='CartTransactionMasters',
        ),
        migrations.RenameModel(
            old_name='CartTransaction',
            new_name='CartTransactions',
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='Categories',
        ),
        migrations.RenameModel(
            old_name='InventoryBalance',
            new_name='InventoryBalances',
        ),
        migrations.RenameModel(
            old_name='InventoryDetail',
            new_name='InventoryDetails',
        ),
        migrations.RenameModel(
            old_name='OrderMaster',
            new_name='OrderMasters',
        ),
        migrations.RenameModel(
            old_name='ProductStoreRating',
            new_name='ProductStoreRatings',
        ),
        migrations.RenameModel(
            old_name='ShippingAgent',
            new_name='ShippingAgents',
        ),
        migrations.RenameModel(
            old_name='ShippingAgentUser',
            new_name='ShippingAgentUsers',
        ),
        migrations.RenameModel(
            old_name='StoreShippingAgent',
            new_name='StoreShippingAgents',
        ),
        migrations.RenameModel(
            old_name='TransactionType',
            new_name='TransactionTypes',
        ),
        migrations.RenameModel(
            old_name='VendorPriceList',
            new_name='VendorPriceLists',
        ),
    ]
