# Generated by Django 3.2.3 on 2021-05-30 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PyCommerce', '0002_gethomeproducts_specificationvaluecount_starpercent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='ImageUrl',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
