# Generated by Django 3.2.4 on 2021-06-16 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PyCommerce', '0002_gethomeproducts_specificationvaluecount_starpercent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermasters',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orders',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
