# Generated by Django 3.2.5 on 2021-07-08 18:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PyCommerce', '0002_gethomeproducts_specificationvaluecount_starpercent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Image4',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
