# Generated by Django 3.2.3 on 2021-05-30 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PyCommerce', '0003_alter_products_imageurl'),
    ]

    operations = [
        migrations.DeleteModel(
            name='starPercent',
        ),
        migrations.AddField(
            model_name='products',
            name='ImageUrl2',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='brands',
            name='NameA',
            field=models.CharField(max_length=2550, null=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='ImageUrl',
            field=models.CharField(max_length=2550, null=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='MainCategoryId',
            field=models.ForeignKey(db_column='MainCategoryId', db_constraint=False, default='null', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.categories'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='NameA',
            field=models.CharField(max_length=2550, null=True),
        ),
        migrations.AlterField(
            model_name='countries',
            name='NameA',
            field=models.CharField(max_length=2550, null=True),
        ),
        migrations.AlterField(
            model_name='ordermasters',
            name='ShippingAdress',
            field=models.CharField(max_length=2550, null=True),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='StatusNameA',
            field=models.CharField(max_length=2550, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='Description',
            field=models.CharField(max_length=2550, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='ImageUrl',
            field=models.CharField(max_length=12550, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='ImageUrl6',
            field=models.CharField(max_length=12550, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='ImageUrl7',
            field=models.CharField(max_length=12550, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='NameA',
            field=models.CharField(max_length=2550, null=True),
        ),
        migrations.AlterField(
            model_name='productstoreratings',
            name='ProductReview',
            field=models.CharField(max_length=2550, null=True),
        ),
        migrations.AlterField(
            model_name='shippingagents',
            name='Adress2',
            field=models.CharField(max_length=2550, null=True),
        ),
        migrations.AlterField(
            model_name='shippingagents',
            name='NameA',
            field=models.CharField(max_length=2550, null=True),
        ),
        migrations.AlterField(
            model_name='shippingagents',
            name='Phone',
            field=models.CharField(max_length=2550, null=True),
        ),
        migrations.AlterField(
            model_name='shippingagents',
            name='PostCode',
            field=models.CharField(max_length=2550, null=True),
        ),
        migrations.AlterField(
            model_name='shippingdetails',
            name='DeliveryNotes',
            field=models.CharField(max_length=2550, null=True),
        ),
        migrations.AlterField(
            model_name='specifications',
            name='NameA',
            field=models.CharField(max_length=2550, null=True),
        ),
        migrations.AlterField(
            model_name='stores',
            name='Address',
            field=models.CharField(max_length=2550, null=True),
        ),
        migrations.AlterField(
            model_name='stores',
            name='Latitude',
            field=models.CharField(max_length=2550, null=True),
        ),
        migrations.AlterField(
            model_name='stores',
            name='Longitude',
            field=models.CharField(max_length=2550, null=True),
        ),
        migrations.AlterField(
            model_name='stores',
            name='NameA',
            field=models.CharField(max_length=2550, null=True),
        ),
        migrations.AlterField(
            model_name='transactiontypes',
            name='NameA',
            field=models.CharField(max_length=2550, null=True),
        ),
        migrations.AlterField(
            model_name='vendors',
            name='Adress2',
            field=models.CharField(max_length=2550, null=True),
        ),
        migrations.AlterField(
            model_name='vendors',
            name='NameA',
            field=models.CharField(max_length=2550, null=True),
        ),
        migrations.AlterField(
            model_name='vendors',
            name='Phone',
            field=models.CharField(max_length=2550, null=True),
        ),
        migrations.AlterField(
            model_name='vendors',
            name='PostCode',
            field=models.CharField(max_length=2550, null=True),
        ),
    ]
