# Generated by Django 3.2.5 on 2021-07-08 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PyCommerce', '0003_alter_products_image4'),
    ]

    operations = [
        migrations.DeleteModel(
            name='getHomeProducts',
        ),
        migrations.DeleteModel(
            name='specificationValueCount',
        ),
        migrations.DeleteModel(
            name='starPercent',
        ),
    ]
