# Generated by Django 3.2.4 on 2021-06-17 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PyCommerce', '0004_auto_20210617_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='MasterId',
            field=models.ForeignKey(db_column='MasterId', on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.carttransactionmasters'),
        ),
    ]
