# Generated by Django 3.2.5 on 2021-07-08 18:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PyCommerce', '0004_auto_20210708_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Image4',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
