# Generated by Django 3.2.3 on 2021-05-30 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PyCommerce', '0004_auto_20210530_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='starPercent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FiveStarsCount', models.FloatField()),
                ('FourStarsCount', models.FloatField()),
                ('ThreeStarsCount', models.FloatField()),
                ('TwoStarsCount', models.FloatField()),
                ('OneStarCount', models.FloatField()),
                ('FiveStarsPercent', models.FloatField()),
                ('FourStarsPercent', models.FloatField()),
                ('ThreeStarsPercent', models.FloatField()),
                ('TwoStarsPercent', models.FloatField()),
                ('OneStarPercent', models.FloatField()),
                ('averageRating', models.FloatField()),
                ('OutOfFive', models.FloatField()),
                ('allReviewsCount', models.IntegerField()),
            ],
            options={
                'db_table': 'GetStarPercent',
                'managed': False,
            },
        ),
    ]
