# Generated by Django 3.2.3 on 2021-05-30 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PyCommerce', '0005_starpercent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='ImageUrl6',
        ),
        migrations.RemoveField(
            model_name='products',
            name='ImageUrl7',
        ),
        migrations.AddField(
            model_name='products',
            name='ImageUrl3',
            field=models.ImageField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='products',
            name='ImageUrl4',
            field=models.ImageField(null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='ImageUrl',
            field=models.ImageField(null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='ImageUrl2',
            field=models.ImageField(null=True, blank=True),
        ),
    ]
