# Generated by Django 3.2.4 on 2021-06-17 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PyCommerce', '0005_alter_orders_masterid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermasters',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='MasterId',
            field=models.ForeignKey(db_column='MasterId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.carttransactionmasters'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
