# Generated by Django 3.2.3 on 2021-05-20 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PyCommerce', '0005_auto_20210520_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='ProductId',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='ShippingAgentId',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='StoreId',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='UserId',
            field=models.IntegerField(),
        ),
    ]
