# Generated by Django 3.2.4 on 2021-06-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PyCommerce', '0006_auto_20210617_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstoreratings',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='gethomeproducts',
            table='gethomeproducts',
        ),
        migrations.AlterModelTable(
            name='specificationvaluecount',
            table='specificationvaluecount',
        ),
        migrations.AlterModelTable(
            name='starpercent',
            table='getstarpercent',
        ),
    ]
