# Generated by Django 3.2.3 on 2021-05-30 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PyCommerce', '0006_auto_20210531_0031'),
    ]

    operations = [
        migrations.DeleteModel(
            name='getHomeProducts',
        ),
        migrations.DeleteModel(
            name='starPercent',
        ),
    ]
