# Generated by Django 3.2.5 on 2021-07-25 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PyCommerce', '0007_auto_20210725_1427'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gethomeproducts',
            options={},
        ),
        migrations.AlterModelOptions(
            name='specificationvaluecount',
            options={},
        ),
        migrations.AlterModelOptions(
            name='starpercent',
            options={},
        ),
    ]
