# Generated by Django 3.2.3 on 2021-05-30 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PyCommerce', '0007_auto_20210531_0034'),
    ]

    operations = [
        migrations.CreateModel(
            name='getHomeProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuantityBalance', models.FloatField()),
                ('ProductName', models.CharField(max_length=2550)),
                ('StoreName', models.CharField(max_length=2550)),
                ('ImageUrl', models.CharField(max_length=2550)),
                ('ImageUrl2', models.CharField(max_length=2550)),
                ('ImageUrl3', models.CharField(max_length=2550)),
                ('ImageUrl4', models.CharField(max_length=2550)),
                ('Description', models.CharField(max_length=2550)),
                ('Price', models.FloatField()),
                ('Currency', models.CharField(max_length=2550)),
                ('PageNumber', models.IntegerField()),
                ('FiveStarsCount', models.FloatField()),
                ('FourStarsCount', models.FloatField()),
                ('ThreeStarsCount', models.FloatField()),
                ('TwoStarsCount', models.FloatField()),
                ('OneStarsCount', models.FloatField()),
                ('MaxTotalRating', models.FloatField()),
                ('finalProductRating', models.FloatField()),
                ('OutOfFivestring', models.FloatField()),
            ],
            options={
                'db_table': 'GetHomeProducts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='starPercent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FiveStarsCount', models.FloatField()),
                ('FourStarsCount', models.FloatField()),
                ('ThreeStarsCount', models.FloatField()),
                ('TwoStarsCount', models.FloatField()),
                ('OneStarCount', models.FloatField()),
                ('FiveStarsPercent', models.FloatField()),
                ('FourStarsPercent', models.FloatField()),
                ('ThreeStarsPercent', models.FloatField()),
                ('TwoStarsPercent', models.FloatField()),
                ('OneStarPercent', models.FloatField()),
                ('averageRating', models.FloatField()),
                ('OutOfFive', models.FloatField()),
                ('allReviewsCount', models.IntegerField()),
            ],
            options={
                'db_table': 'GetStarPercent',
                'managed': False,
            },
        ),
        migrations.RenameField(
            model_name='products',
            old_name='ImageUrl',
            new_name='Image',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='ImageUrl2',
            new_name='Image2',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='ImageUrl3',
            new_name='Image3',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='ImageUrl4',
            new_name='Image4',
        ),
    ]
