# Generated by Django 3.2.4 on 2021-06-03 13:07

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('PyCommerce', '0008_auto_20210531_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=100, size=[300, 200], upload_to=''),
        ),
        migrations.AlterField(
            model_name='products',
            name='Image2',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=100, size=[300, 200], upload_to=''),
        ),
        migrations.AlterField(
            model_name='products',
            name='Image3',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=100, size=[300, 200], upload_to=''),
        ),
        migrations.AlterField(
            model_name='products',
            name='Image4',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=100, size=[300, 200], upload_to=''),
        ),
    ]
