# Generated by Django 3.2.3 on 2021-05-20 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PyCommerce', '0008_auto_20210520_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='getHomeProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StoreId', models.IntegerField()),
                ('ProductId', models.IntegerField()),
                ('QuantityBalance', models.FloatField()),
                ('ProductName', models.CharField(max_length=2550)),
                ('StoreName', models.CharField(max_length=2550)),
                ('ImageUrl', models.CharField(max_length=2550)),
                ('ImageUrl6', models.CharField(max_length=2550)),
                ('ImageUrl7', models.CharField(max_length=2550)),
                ('Description', models.CharField(max_length=2550)),
                ('Price', models.FloatField()),
                ('Currency', models.CharField(max_length=2550)),
                ('CategoryId', models.IntegerField()),
                ('PageNumber', models.IntegerField()),
                ('FiveStarsCount', models.FloatField()),
                ('FourStarsCount', models.FloatField()),
                ('ThreeStarsCount', models.FloatField()),
                ('TwoStarsCount', models.FloatField()),
                ('OneStarsCount', models.FloatField()),
                ('MaxTotalRating', models.FloatField()),
                ('finalProductRating', models.FloatField()),
                ('OutOfFivestring', models.FloatField()),
            ],
            options={
                'db_table': 'GetHomeProducts',
                'managed': False,
            },
        ),
    ]
