# Generated by Django 3.2.4 on 2021-06-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PyCommerce', '0008_alter_products_image4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Image4',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
