# Generated by Django 3.2.4 on 2021-06-03 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PyCommerce', '0009_auto_20210603_1507'),
    ]

    operations = [
        migrations.DeleteModel(
            name='getHomeProducts',
        ),
        migrations.DeleteModel(
            name='starPercent',
        ),
    ]
