# Generated by Django 3.2.3 on 2021-05-20 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PyCommerce', '0009_gethomeproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='ImageUrl',
            field=models.CharField(blank=True, max_length=2550),
        ),
    ]
