# Generated by Django 3.2.4 on 2021-06-25 13:04

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PyCommerce', '0009_alter_products_image4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Image4',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
