# Generated by Django 3.2.5 on 2021-07-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PyCommerce', '0009_auto_20210725_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Image4',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
