# Generated by Django 3.2.4 on 2021-06-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PyCommerce', '0010_alter_products_image4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstoreratings',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
