# Generated by Django 3.2.4 on 2021-06-03 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PyCommerce', '0011_gethomeproducts_starpercent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermasters',
            name='cartId',
            field=models.ForeignKey(db_column='CartId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.carttransactions'),
        ),
    ]
