# Generated by Django 3.2.5 on 2021-07-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PyCommerce', '0011_alter_categories_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Phone',
            field=models.TextField(max_length=11, null=True),
        ),
    ]
