# Generated by Django 3.2.5 on 2021-07-31 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PyCommerce', '0012_alter_users_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
