# Generated by Django 3.2.4 on 2021-06-03 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PyCommerce', '0012_alter_ordermasters_cartid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='ShippingAgentId',
            field=models.ForeignKey(db_column='ShippingAgentId', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.shippingagents'),
        ),
    ]
