# Generated by Django 3.2.4 on 2021-06-05 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PyCommerce', '0013_alter_orders_shippingagentid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendors',
            old_name='Adress1',
            new_name='Address1',
        ),
        migrations.RenameField(
            model_name='vendors',
            old_name='Adress2',
            new_name='Address2',
        ),
    ]
