# Generated by Django 3.2.3 on 2021-05-21 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PyCommerce', '0013_alter_stores_shippingagentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='MainCategoryId',
            field=models.ForeignKey(blank=True, db_column='MainCategoryId', on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.categories'),
        ),
    ]
