# Generated by Django 3.2.4 on 2021-06-05 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PyCommerce', '0014_auto_20210606_0015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermasters',
            old_name='ShippingAdress',
            new_name='ShippingAddress',
        ),
        migrations.RenameField(
            model_name='shippingagents',
            old_name='Adress1',
            new_name='Address1',
        ),
        migrations.RenameField(
            model_name='shippingagents',
            old_name='Adress2',
            new_name='Address2',
        ),
    ]
