# Generated by Django 3.2.4 on 2021-06-06 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PyCommerce', '0015_auto_20210606_0019'),
    ]

    operations = [
        migrations.DeleteModel(
            name='specificationValueCounts',
        ),
    ]
