# Generated by Django 3.2.5 on 2021-08-03 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PyCommerce', '0018_alter_products_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorydetails',
            name='TransType',
            field=models.ForeignKey(db_column='TransType', db_constraint=False, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.transactiontypes'),
        ),
        migrations.AlterField(
            model_name='products',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
