# Generated by Django 3.2.5 on 2021-08-15 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PyCommerce', '0019_auto_20210803_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='MasterId',
            field=models.ForeignKey(db_column='MasterId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.ordermasters'),
        ),
    ]
