# Generated by Django 4.2.4 on 2023-08-13 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PyCommerce', '0020_alter_orders_masterid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='MainCategoryId',
            field=models.ForeignKey(blank=True, db_column='MainCategoryId', db_constraint=False, default='null', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.categories'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='cartId',
            field=models.ForeignKey(db_column='CartId', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='PyCommerce.carttransactionmasters'),
        ),
    ]
