# Generated by Django 4.2.4 on 2023-08-13 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PyCommerce', '0023_delete_gethomeproducts_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'managed': False},
        ),
    ]
