# Generated by Django 4.2.4 on 2023-08-13 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PyCommerce', '0024_alter_categories_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='getHomeProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuantityBalance', models.FloatField()),
                ('ProductName', models.TextField(max_length=2550)),
                ('StoreName', models.TextField(max_length=2550)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='')),
                ('Image2', models.ImageField(blank=True, null=True, upload_to='')),
                ('Image3', models.ImageField(blank=True, null=True, upload_to='')),
                ('Image4', models.ImageField(blank=True, null=True, upload_to='')),
                ('Description', models.TextField(max_length=2550)),
                ('Price', models.FloatField()),
                ('Currency', models.TextField(max_length=2550)),
                ('PageNumber', models.IntegerField()),
                ('FiveStarsCount', models.FloatField()),
                ('FourStarsCount', models.FloatField()),
                ('ThreeStarsCount', models.FloatField()),
                ('TwoStarsCount', models.FloatField()),
                ('OneStarsCount', models.FloatField()),
                ('MaxTotalRating', models.FloatField()),
                ('finalProductRating', models.FloatField()),
                ('OutOfFivestring', models.FloatField()),
            ],
            options={
                'db_table': 'gethomeproducts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='specificationValueCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SpecificationId', models.IntegerField()),
                ('SpecificationValue', models.TextField(max_length=2550)),
                ('SpecificationCount', models.IntegerField()),
                ('CategoryId', models.IntegerField()),
            ],
            options={
                'db_table': 'specificationvaluecount',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='starPercent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FiveStarsCount', models.FloatField()),
                ('FourStarsCount', models.FloatField()),
                ('ThreeStarsCount', models.FloatField()),
                ('TwoStarsCount', models.FloatField()),
                ('OneStarCount', models.FloatField()),
                ('FiveStarsPercent', models.FloatField()),
                ('FourStarsPercent', models.FloatField()),
                ('ThreeStarsPercent', models.FloatField()),
                ('TwoStarsPercent', models.FloatField()),
                ('OneStarPercent', models.FloatField()),
                ('averageRating', models.FloatField()),
                ('OutOfFive', models.FloatField()),
                ('allReviewsCount', models.IntegerField()),
            ],
            options={
                'db_table': 'getstarpercent',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='categories',
            options={},
        ),
    ]
