# Generated by Django 4.2.4 on 2023-08-14 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PyCommerce', '0025_gethomeproducts_specificationvaluecount_starpercent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gethomeproducts',
            options={},
        ),
        migrations.AlterModelOptions(
            name='specificationvaluecount',
            options={},
        ),
        migrations.AlterModelOptions(
            name='starpercent',
            options={},
        ),
    ]
